#数据库连接
spring: 
    thymeleaf: 
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: LEGACYHTML5
    datasource: 
        url: jdbc:mysql://localhost:3306/park_sbt?characterEncoding=utf8&useSSL=true 
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
#服务器端口
server: 
  port: 8080
  